#! /bin/bash

links="bash_profile bashrc dir_colors Xdefaults xsession xinit xinitrc vim vim/vimrc vim/gvimrc conkyrc"
path=$(pwd)

[ ! -e backup ] && mkdir backup

for i in $links
do
	dest=~/.$(basename $i)
	[ -e $dest ] && [ ! -h $dest ] && mv $dest backup
	ln -sf $path/$i $dest
done
